markdown: kramdown
title: Facebook4J - A Java library for the Facebook Graph API
description: Facebook4J is a Java library for the Facebook Graph API. This library provides the ease of use like Twitter4J. Facebook4J is an unofficial library.
keywords: facebook,java,facebook4j
author:
  name: roundrop
name: Facebook4J
